# Generated by Django 3.0.8 on 2020-07-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('age', models.FloatField(blank=True)),
                ('date_arrival', models.DateField()),
                ('weight', models.FloatField(blank=True)),
                ('height', models.FloatField(blank=True)),
                ('special_mark', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
            ],
        ),
    ]
