# Generated by Django 3.0.8 on 2020-07-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='photo',
        ),
    ]
